version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.dropwizard.metrics:metrics-core
    versions:
    - 4.1.17
    - 4.1.18
    - 4.1.19
  - dependency-name: com.google.protobuf:protobuf-java
    versions:
    - 3.14.0
    - 3.15.0
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-annotations
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: com.fasterxml.jackson.core:jackson-core
    versions:
    - 2.12.1
    - 2.12.2
  - dependency-name: org.eclipse.jetty:jetty-util
    versions:
    - 9.4.18.v20190429
  - dependency-name: org.eclipse.jetty:jetty-server
    versions:
    - 9.4.18.v20190429
  - dependency-name: org.eclipse.jetty:jetty-security
    versions:
    - 9.4.18.v20190429
  - dependency-name: org.eclipse.jetty:jetty-http
    versions:
    - 9.4.18.v20190429
  - dependency-name: kr.motd.maven:os-maven-plugin
    versions:
    - 1.6.2
